# Generated by Django 3.1.1 on 2020-09-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('newprice', models.IntegerField()),
                ('oldprice', models.IntegerField()),
                ('image', models.CharField(max_length=2000)),
            ],
        ),
    ]
