# Generated by Django 3.1.1 on 2020-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0002_auto_20200920_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arrtribute',
            field=models.TextField(default=0, max_length=1000, verbose_name='attribute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='newprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.FloatField(),
        ),
    ]
