# Generated by Django 3.1.1 on 2020-09-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0004_auto_20200921_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=0, max_length=1000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default=0, max_length=1000, verbose_name='features'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='imagepr1',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='imagepr2',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='imagepr3',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='imagepr4',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
