# Generated by Django 3.1.1 on 2020-09-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0006_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
