# Generated by Django 3.1.1 on 2020-10-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0007_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagefull_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
