# Generated by Django 3.1.1 on 2020-10-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0008_product_imagefull_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagefull_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
