# Generated by Django 3.1.1 on 2020-10-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0009_product_imagefull_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagefull_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='imagefull_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
