# Generated by Django 3.1.1 on 2020-10-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0010_auto_20201004_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagepr1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagepr2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagepr3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagepr4',
        ),
    ]
