# Generated by Django 3.1.1 on 2020-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0011_auto_20201004_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
