# Generated by Django 3.1.1 on 2020-10-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0013_shippingaddress_payment_stauts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='payment_stauts',
            new_name='payment_status',
        ),
    ]
