# Generated by Django 3.1.1 on 2020-10-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0015_shippingaddress_payment_cod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='payment_Cod',
            new_name='payment_cod',
        ),
    ]
