# Generated by Django 3.1.1 on 2020-10-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0016_auto_20201018_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderitem_status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
